name: Nightly Build
on:
  schedule:
    # Random minute number to avoid GH scheduler stampede
    - cron: '37 21 * * *'
  workflow_dispatch: {}
permissions:
  contents: read
  packages: write

jobs:
  build-and-publish-images:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build images
        run: make help
